highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://biomadeira.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: "/"
title: Jiawei Jiang's Resume
name: Jiawei Jiang
email: jiawei.jiang@whu.edu.cn
email_full: mailto:jiawei.jiang@whu.edu.cn
website: bluesjjw.github.io
website_full: https://bluesjjw.github.io/
github: bluesjjw
twitter: twitter
tel: +41 044 632 3211
tel_full: tel:+41 044 632 3211
google_maps: 'https://www.google.com/maps/place/Wuhan+University'
address: No. 299, Bayi Road
postcode: 430072
city: Wuhan
country: China
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
